version: '3'
services:
    db:
        image: "mysql:8"
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/conf:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: twh
            MYSQL_USER: symfony
            MYSQL_PASSWORD: secret